# Generated by Django 4.1.1 on 2022-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_phone', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=12)),
                ('student_course', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
