# Generated by Django 4.1.1 on 2022-09-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.manager'),
        ),
    ]
