# Generated by Django 4.1.1 on 2022-09-21 11:39

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='manager',
            field=models.ForeignKey(default=user.models.Student.rand_manager, on_delete=django.db.models.deletion.PROTECT, to='user.manager'),
        ),
    ]
